### ISSUE TITLE
Trinkets (with Honor Talents)

### ISSUE THREAD

**Issue by nfgallimore** [stako/sArena#12]
Trinkets don't work, do you plan on implementing them with the new honor talents? Is it possible with their functionality?

**Comment by stako** [comment]
I think it's just Adaptation? Will fix shortly.

**Comment by nfgallimore** [comment]
Adaptation works now with the version on curse. Also DH sap is not showing on DR list and there are no overlay icons that show when a person is CC'd. The overlay is pretty important because I cannot tell when an enemy is sitting in a polymorph until it ends and I see the DR pop up.

**Comment by stako** [comment]
Using new Blizz trinkets now.
