### ISSUE TITLE
sArena 3.3.5 version

### ISSUE THREAD

**Issue by Qblolz** [stako/sArena#13]
Can you do a 3.3.5 version - I can`t make a move ArenaEnemyXCastBar and pernamently showing at test mode -> [link 3.3.5 version](http://www.mediafire.com/file/mvvrdvhmtuona8d/sArena.rar)
Can yo help?

**Comment by stako** [comment]
I would need 3.3.5 installed in order to make a version of sArena for it. Not happpening. You'll have to fix it yourself or find somebody else who can. Sorry.
