### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Haagen-Dazs** [stako/sArena#26]
3x [ADDON_ACTION_BLOCKED] AddOn 'sArena' tried to call the protected function 'ArenaEnemyFrame2:SetPoint()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetPoint'
Blizzard_ArenaUI\Blizzard_ArenaUI.lua:180: in function <Blizzard_ArenaUI\Blizzard_ArenaUI.lua:147>
[C]: in function `ArenaEnemyFrame_UpdatePlayer'
Blizzard_ArenaUI\Blizzard_ArenaUI.lua:224: in function <Blizzard_ArenaUI\Blizzard_ArenaUI.lua:218>

Locals:
InCombatSkipped

**Comment by stako** [comment]
Fixed in sArena 3 rewrite
