### ISSUE TITLE
Can't move arena frames after update

### ISSUE THREAD

**Issue by Hessutar** [stako/sArena#28]
Hello, great addon first of all.

After the 3.0.0 update I can't seem to move arena frames with shift + ctrl and click to move.
Also the normal blizzard UI frames are showing and not hidden. Not sure if only my problem.

I reverted back to 2.0.8 and it worked normally again.

-Hessu

**Comment by stako** [comment]
For versions older than sArena 3, it didn't hide the Blizzard frames, but actually used them and added functionality to them. sArena 3 no longer relies on the Blizzard frames and doesn't touch them whatsoever. I'll look into adding an option to hide the Blizz frames.

With this rewrite, the frames can be moved in the sArena settings window. Will add the drag functionality back in later.

**Comment by Hessutar** [comment]
Alright. Thanks for the info!
