### ISSUE TITLE
Blizzard Arena Frames displayed after match

### ISSUE THREAD

**Issue by raphaeloliveira** [stako/sArena#36]
Hi, I'm using sArena and I noticed that after leaving the game, the Blizzard default arena frame is displayed in my UI. They don't actually show up during the game, just after it.

Reloading my UI fixes it but I was wondering if there is a way to remove that behaviour.

Example:
![WoWScrnShot_122519_122737](https://user-images.githubusercontent.com/2700131/71428014-0a10f700-2712-11ea-9ac1-6c17ec81b9b2.jpg)

**Comment by stako** [comment]
Does it happen when sArena is the only addon enabled? If no, which addon is causing the conflict?

**Comment by stako** [comment]
Fixed with version 3.1.2 for users of ElvUI
