### ISSUE TITLE
UI reset

### ISSUE THREAD

**Issue by socketubs** [stako/sArena#4]
I'm not sure but this sort of bug never append without sArena.
My UI just reset at default position (I just move my frame and target frame, not so much customization).

Sometime, I log in and these frames have been reset.
Any idea ? How can I help ?

**Comment by stako** [comment]
This happens to me whenever I try to log in and the world server is down,
even without any addons. Did that happen to you by chance?

**Comment by socketubs** [comment]
Yes! Exactly!
World server has been down just right now. :+1:

**Comment by socketubs** [comment]
Just found it: http://eu.battle.net/wow/en/forum/topic/12618122505
