### ISSUE TITLE
Flat Layout

### ISSUE THREAD

**Issue by Purple0203** [stako/sArena#46]
I just saw that you took the flat layout out of the addon and i wonder if there is a way to get it back in. i tried to copy the code that you deleted, made a new LUA in the Layouts section of the addon and paste it but it looks like that doesnt make it. Could you help me out with that? I really loved the flat layout and would love to get it back, helped me alot! If you dont want it to be part of the addon for everyone, could you just "show" me how i get it back? Much love!

**Comment by stako** [comment]
This layout will soon be available for download on CurseForge [here.](https://www.curseforge.com/wow/addons/sarena-layout-flat) It's just pending moderator approval.
