### ISSUE TITLE
Getting decimal to Crowd Controls

### ISSUE THREAD

**Issue by Bisonpasfute** [stako/sArena#51]
Hello there, 

This isn't an issue but more of a suggestion. 

Back in an older version (3.0.11) of sArena, we could see decimals when the remaining time of a crowd control was less than 5 seconds but it's not the case anymore. I tried to tweak the code and managed to find the code that did it back then but too many changes happened since then that made it impossible for me to make it work again. 

Thus my demand : would it be possible to add an option to add decimals again, or simply bring them back ?

Thanks again for your work !

**Comment by stako** [comment]
In the older version which you'd noted, some of the numbers being displayed on cooldown icons were created & managed by sArena. In newer versions, it is managed by other sources - typically either by the built-in Blizzard cooldown text, or by OmniCC. Won't be reverting back. OmniCC provides a way to include tenths of a second in the cooldown text.
