### ISSUE TITLE
TBC Sarena Version- Cant move main profiles

### ISSUE THREAD

**Issue by bounceback295** [stako/sArena#54]
**Describe the bug**
When trying to move the main class profile frames, the profiles aren't moving even when I am pressing ctrl shift click.

**Expected behavior**
When ctrl shift clicking I expected the frames to move where I wanted.

**Comment by stako** [comment]
Blizzard introduced some new restrictions to addons a few days ago which broke this. Should be fixed in version 1.8 or newer.
