### ISSUE TITLE
Question: Does this repo contain the TBC version of the addon?

### ISSUE THREAD

**Issue by nazrhom** [stako/sArena#56]
First of all, thank you for writing and maintaining this. I've just started learning about how WoW addons work, and thought I would have a look at the source code for this one to read and learn from.
I play TBC and through curse saw that the addon links to this repo, however the version that I see here on `master` seems to be for retail. Do you have any pointers about how this works?

Thanks in advance for the help and keep up the great work!

**Comment by stako** [comment]
TBC version was never uploaded to Github. Can still be downloaded from the Curse page though.
