### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by pascal-mueller** [stako/sArena#62]
Hello,

it seems this project isn't maintained anymore, at least that's what curse says. Is this true? If it is true, are you interested in letting someone else take over?

**Comment by stako** [comment]
Yes that's correct. 

Others are free to continue working on the addon or use it as a basis for their own addons, subject to the restrictions of the [MIT license](https://github.com/stako/sArena/blob/master/LICENSE.txt) under which sArena is made available.
